AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  A SAM application for a conceptual eSewa Allottee REST API.

# Global settings for all functions
Globals:
  Function:
    Timeout: 10 # Timeout in seconds
    MemorySize: 128 # Memory in MB
    Runtime: python3.9

Resources:
  # Define the Lambda Function
  GetAllotteeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/  # Path to the folder containing the function code
      Handler: app.lambda_handler # The file and method to execute: app.py -> lambda_handler
      Events:
        # This section defines the API Gateway trigger
        GetAllotteeApi:
          Type: Api
          Properties:
            Path: /allottees/{employeeId}
            Method: get

Outputs:
  # This section provides the deployed API endpoint as an output
  AllotteeApiEndpoint:
    Description: "API Gateway endpoint URL for Prod stage for Allottee function"
    Value: !Sub "https://://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/allottees/"
